package vista;

import javax.swing.JFrame;
import services.TranslationService;
public class GameSelectorGUI extends javax.swing.JFrame {

    public GameSelectorGUI(JFrame parent, TranslationService translationService) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMinesweeper = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3Raya = new javax.swing.JButton();
        jButton4Raya1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonMinesweeper.setText(org.openide.util.NbBundle.getMessage(GameSelectorGUI.class, "GameSelectorGUI.jButtonMinesweeper.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GameSelectorGUI.class, "GameSelectorGUI.jLabel1.text")); // NOI18N

        jButton3Raya.setText(org.openide.util.NbBundle.getMessage(GameSelectorGUI.class, "GameSelectorGUI.jButton3Raya.text")); // NOI18N

        jButton4Raya1.setText(org.openide.util.NbBundle.getMessage(GameSelectorGUI.class, "GameSelectorGUI.jButton4Raya1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMinesweeper, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(242, 242, 242))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton3Raya, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(200, 200, 200)))
                    .addComponent(jButton4Raya1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jButton3Raya, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton4Raya1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonMinesweeper, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3Raya;
    private javax.swing.JButton jButton4Raya1;
    private javax.swing.JButton jButtonMinesweeper;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
