/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package juego;

import javax.swing.JFrame;
import model.Usuari;
import services.TranslationService;

/**
 *
 * @author Admin
 */
public class ElegirSimbolo extends javax.swing.JDialog {
    private JFrame parent;
    private Usuari user;
    private TranslationService translationService;
    private boolean juego;
    /**
     * Creates new form ElegirSimbolo
     */
    public ElegirSimbolo(java.awt.Frame parent,TranslationService translationService, Usuari user,  boolean juego) {
        super(parent);
        this.translationService = translationService;
        this.user = user;
        this.juego = juego;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonO = new javax.swing.JButton();

        jButton2.setText(org.openide.util.NbBundle.getMessage(ElegirSimbolo.class, "ElegirSimbolo.jButton2.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonX.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonX.setForeground(new java.awt.Color(255, 0, 0));
        jButtonX.setText(org.openide.util.NbBundle.getMessage(ElegirSimbolo.class, "ElegirSimbolo.jButtonX.text")); // NOI18N
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ElegirSimbolo.class, "ElegirSimbolo.jLabel1.text")); // NOI18N

        jButtonO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonO.setForeground(new java.awt.Color(51, 51, 255));
        jButtonO.setText(org.openide.util.NbBundle.getMessage(ElegirSimbolo.class, "ElegirSimbolo.jButtonO.text")); // NOI18N
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        if (!juego) {
            CuatroEnRaya connect4 = new CuatroEnRaya(parent, translationService, user, true);
            connect4.setVisible(true);
        }else{
            TresEnRaya connect4 = new TresEnRaya(parent, translationService, user, true);
            connect4.setVisible(true);
        }
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        if (!juego) {
            CuatroEnRaya connect4 = new CuatroEnRaya(parent, translationService, user, false);
            connect4.setVisible(true);
        }else{
            TresEnRaya connect4 = new TresEnRaya(parent, translationService, user, false);
            connect4.setVisible(true);
        }
    }//GEN-LAST:event_jButtonOActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonX;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
