package juego;

import javax.swing.JFrame;
import model.Usuari;
import services.TranslationService;


public class ElegirSimbolo extends javax.swing.JDialog {

    private JFrame parent;
    private Usuari user;
    private TranslationService translationService;
    private boolean juego;


    public ElegirSimbolo(JFrame parent, TranslationService translationService, Usuari user, boolean juego) {
        this.parent = parent;
        this.translationService = translationService;
        this.user = user;
        this.juego = juego;
        initComponents();
        translatePage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonO = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jLabelText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonO.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonO.setForeground(new java.awt.Color(0, 0, 255));
        jButtonO.setText("O");
        jButtonO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });

        jButtonX.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButtonX.setForeground(new java.awt.Color(255, 0, 0));
        jButtonX.setText("X");
        jButtonX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jLabelText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelText.setText("Elige un símbolo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelText, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelText)
                .addGap(40, 40, 40)
                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        if (juego == false) {
            CuatroEnRaya connect4 = new CuatroEnRaya(parent, translationService, user, false);
            connect4.setVisible(true);
            this.dispose();
        } else {
            TresEnRaya connect4 = new TresEnRaya(parent, translationService, user, false);
            connect4.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonOActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        if (juego == false) {
            CuatroEnRaya connect4 = new CuatroEnRaya(parent, translationService, user, true);
            connect4.setVisible(true);
        } else {
            TresEnRaya connect4 = new TresEnRaya(parent, translationService, user, true);
            connect4.setVisible(true);
        }
    }//GEN-LAST:event_jButtonXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonX;
    private javax.swing.JLabel jLabelText;
    // End of variables declaration//GEN-END:variables

    private void translatePage() {
        jLabelText.setText(translationService.translate("{CHOOSESYMBOL}"));
    }
}
